export const movies = [
  {
    id: 101,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(154, 51, 250, 0.2)",
  },
  {
    id: 102,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(250, 201, 51, 0.2)",
  },
  {
    id: 103,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(51, 144, 250, 0.2)",
  },
  {
    id: 104,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(250, 97, 51, 0.2)",
  },
  {
    id: 105,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(51, 241, 250, 0.2)",
  },
  {
    id: 106,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(217, 250, 51, 0.2)",
  },
  {
    id: 107,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(127, 51, 250, 0.2)",
  },
  {
    id: 108,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(51, 218, 108, 0.2)",
  },
  {
    id: 109,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(51, 125, 108, 0.2)",
  },
];

export const latest = [
  {
    id: 201,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(254, 51, 250, 0.2)",
  },
  {
    id: 202,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(250, 201, 151, 0.2)",
  },
  {
    id: 203,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(51, 144, 150, 0.2)",
  },
  {
    id: 204,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(250, 97, 91, 0.2)",
  },
  {
    id: 205,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(151, 241, 250, 0.2)",
  },
  {
    id: 206,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(217, 250, 250, 0.2)",
  },
  {
    id: 207,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(127, 51, 150, 0.2)",
  },
  {
    id: 208,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(51, 118, 108, 0.2)",
  },
  {
    id: 209,
    title: "The Witcher",
    subtitle: "Nightmare of the Wolf",
    description: "The Witcher Nightmare of the Wolf description",
    color: "rgba(51, 125, 108, 0.2)",
  },
];
